# Generated by Django 4.2.5 on 2024-03-19 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('price', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sweetener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.product')),
                ('flavours', models.ManyToManyField(blank=True, to='cafe.flavour')),
                ('sweeteners', models.ManyToManyField(blank=True, to='cafe.sweetener')),
                ('toppings', models.ManyToManyField(blank=True, to='cafe.topping')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('Small', 'SMALL'), ('Medium', 'MEDIUM'), ('Large', 'LARGE')], max_length=20)),
                ('quantity_small', models.CharField(blank=True, max_length=4)),
                ('quantity_medium', models.CharField(blank=True, max_length=4)),
                ('quantity_large', models.CharField(blank=True, max_length=4)),
                ('temperature', models.CharField(blank=True, default=75, max_length=4)),
                ('brewing_method', models.CharField(blank=True, max_length=100)),
                ('roast_level', models.CharField(blank=True, choices=[('Light', 'LIGHT'), ('Medium', 'MEDIUM'), ('Medium-Darj', 'MEDIUM-DARK'), ('Dark', 'DARK'), ('Espresso', 'ESPRESSO')], max_length=20)),
                ('milk_type', models.CharField(blank=True, max_length=50)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.product')),
            ],
        ),
    ]
