# Generated by Django 4.2.5 on 2024-03-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Coffee', 'COFFEE'), ('Tea', 'TEA'), ('Milkshake', 'MILKSHAKE'), ('Smoothie', 'SMOOTHIE')], default='Coffee', max_length=20),
        ),
        migrations.AlterField(
            model_name='productcustomization',
            name='roast_level',
            field=models.CharField(blank=True, choices=[('Light', 'LIGHT'), ('Medium', 'MEDIUM'), ('Medium-Dark', 'MEDIUM-DARK'), ('Dark', 'DARK'), ('Espresso', 'ESPRESSO')], max_length=20),
        ),
    ]
