# Generated by Django 4.2.5 on 2024-03-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favourited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Coffee', 'COFFEE'), ('Tea', 'TEA'), ('Milkshake', 'MILKSHAKE'), ('Smoothie', 'SMOOTHIE'), ('Other', 'OTHER')], default='Other', max_length=20),
        ),
    ]
